INSERT INTO estado(nombre) VALUES('DISPONIBLE');
INSERT INTO estado(nombre) VALUES('ALQUILADO');
INSERT INTO estado(nombre) VALUES('REPARACIÓN');
INSERT INTO categoria(nombre)VALUES('Familiar');
INSERT INTO categoria(nombre) VALUES('Deportivo');
INSERT INTO categoria(nombre) VALUES('Lujo');
INSERT INTO marca(nombre) VALUES('CHEVROLET');
INSERT INTO marca(nombre) VALUES('HUNDAY');
INSERT INTO marca(nombre) VALUES('MERCEDES VENZ');
INSERT INTO marca(nombre) VALUES('CAMARO');
INSERT INTO modelo(id_marca,nombre) VALUES(1,'AVEO');
INSERT INTO modelo(id_marca,nombre) VALUES(1,'CAUTIVA');
INSERT INTO modelo(id_marca,nombre) VALUES(1,'TAHOE');
INSERT INTO modelo(id_marca,nombre) VALUES(2,'TUCSON H3');
INSERT INTO modelo(id_marca,nombre) VALUES(3,'COUPÉ');
INSERT INTO modelo(id_marca,nombre) VALUES(4,'OPTIMUS PRIME');
INSERT INTO modelo(id_marca,nombre) VALUES(3,'CAMPER');
INSERT INTO modelo(id_marca,nombre) VALUES(1,'TRACKER TURBO');
INSERT INTO modelo(id_marca,nombre) VALUES(1,'COLORADO');
INSERT INTO modelo(id_marca,nombre) VALUES(1,'MONTANA');
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(1,1,1,'BDC-4859',5,800,'blanco',75.25);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(2,1,7,'BDO-4259',2,1500,'plata',150.50);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(1,1,2,'BDJ-0259',8,1100,'gris claro',100.50);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(2,1,8,'FDJ-1259',5,1700,'verde oscuro',95.50);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(1,1,10,'FMJ-2259',8,900,'rojo',75.80);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(2,1,9,'FKJ-9359',6,1400,'blanco',99.80);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(1,1,6,'LKJ-0259',6,500,'azul',60.80);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(3,1,5,'IKJ-0553',2,1500,'azul platino',160.80);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(1,1,4,'OKJ-4753',6,1100,'blanco',100.80);
INSERT INTO auto(id_categoria,id_estado,id_modelo,matricula,capacidad,potencia,color,precio_diario) VALUES(1,1,3,'KÑJ-1253',8,1300,'negra',120.80);
